pipeline {
  agent {
    docker {
       //image '10.11.6.26/amd64/centos7:latest'
       image 'ccr.ccs.tencentyun.com/topsec/centos7-base:amd64'
       //image 'actanble/centos7-base:amd64'
       label 'master'
//        args  '-v `pwd`:/home/ngos/workspace -w /home/ngos/workspace'
    }
  }

  environment {
	  //RELEASE_SITE_DIR = "https://raw.githubusercontent.com/yofua/ci-pkgs/pkgs/ngx-deps/"
	  RELEASE_SITE_DIR = "https://git.weixin.qq.com/redau/devops-pkgs/raw/pkgs/ngx-deps/"
      BUILD_COMP_TAG = "nginx-xc.x84_64"
      NGINX_ALIAS_NAME = "nginx"

      //GIT_REPO_URL = "https://10.7.202.199/filestore/ngx-deps/"
	  //GIT_BUILD_REF = "*/master"
	  //CREDENTIALS_ID = "211_gitlab_xx"
  }

  options {
	  parallelsAlwaysFailFast()
      // skipDefaultCheckout()
      timestamps()
      disableConcurrentBuilds()
      // buildDiscarder(logRotator(numToKeepStr: '3'))
  }

 triggers {
    pollSCM('H */4 * * 1-5')
  }

  stages {

    stage("分支检出 (CheckOut)") {
      steps {

        echo 'checkout current branch jenkins file'
        checkout([
            $class: 'GitSCM',
            branches: [[name: env.GIT_BUILD_REF]],
            userRemoteConfigs: [[url: env.GIT_REPO_URL, credentialsId: env.CREDENTIALS_ID]]]
        ])

      }
    }

    stage('环境测试') {
      parallel {

        stage('1. 查看和验证环境') {
          steps {
            script {
              sh 'uname -a'
              // sh "sed -i 's/\r//' ./auxil/rhel7_prepare.sh && bash ./auxil/rhel7_prepare.sh"
            }
          }
        }

        stage('2. 测试环境变量OK') {
          when {
            branch 'dev'
            environment name: 'DOCKER_IMAGE_TAG', value: 'dev'
          }
        steps {
            script {
              sh "echo 1"
              sh "echo 22"
              sh "echo 333"
            }
          }
        }

      }
    }

    stage('构建组件包') {
      steps {
        //sh "yum -y install devtoolset-7"
        //sh "scl enable devtoolset-7 bash"
        sh "sed -i 's/\r//' ./modsecurity.sh && bash ./modsecurity.sh"
      }
    }

    stage('构建后的操作') {
      steps {
        // 推送镜像到远程仓库
        sh "rm -rf ./nginx/conf/ && /usr/bin/cp -r ./conf/ ./nginx/"
        sh "rm -rf ./nginx/html/ && /usr/bin/cp -r ./html/ ./nginx/"
        sh "/usr/bin/cp ./nginx.sh ./nginx/"
        sh "sed -i 's/\r//' ./nginx/nginx.sh && chmod u+x ./nginx/nginx.sh"
        //sh 'yum -y install patchelf'
      }
    }

    stage('打包并上传') {
        environment {
            BUILD_COMP_TIMESTAMP = """${
                   sh(
                           returnStdout: true,
                           script: 'echo -n "$(date +%Y%m%d).${BUILD_ID}"'
                   )
               }"""
        }

      steps {
        // 推送镜像到远程仓库
        sh "tar czf ${BUILD_COMP_TAG}-${BUILD_COMP_TIMESTAMP}.tar.gz nginx"
        sh "ls -alh ${BUILD_COMP_TAG}-${BUILD_COMP_TIMESTAMP}.tar.gz"
        // sh "curl --progress-bar -k -T ${BUILD_COMP_TAG}-${BUILD_COMP_TIMESTAMP}.tar.gz https://10.7.202.199/filestore/builds/ | tee /dev/null"

        echo "Build Comp OK!"

      }
    }

 }

  post {
        always {
            echo "Topsec BigData Licence v1 For BdTech. IC"
        }
    }

}
